version: "3.3"
services:
  musci-library-api-file-db:
    container_name: musci-library-api-file-mysql-db
    image: mysql:5.7
    restart: always
    command: --sql_mode="NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_DATABASE: "musci_library_api_file_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - vol-musci-library-api-file-db:/var/lib/mysql
volumes:
  vol-musci-library-api-file-db:
